services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6739:6739'
    volumes:
      - redis_data:/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg_data:
  redis_data:
